### ISSUE TITLE
login error: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by Xidai** [weflex/neaty#4]
when login with username and password, the error occurs.

```
TypeError: Cannot read property 'create' of undefined
    at ModelConstructor.User.createAccessToken (/Users/daixi/Documents/Code/weflex-api/node_modules/neaty/common/models/user.js:95:22)
    at /Users/daixi/Documents/Code/weflex-api/node_modules/neaty/common/models/user.js:251:22
    at /Users/daixi/Documents/Code/weflex-api/node_modules/neaty/common/models/user.js:307:9
    at /Users/daixi/Documents/Code/weflex-api/node_modules/bcryptjs/dist/bcrypt.js:261:17
    at /Users/daixi/Documents/Code/weflex-api/node_modules/bcryptjs/dist/bcrypt.js:1198:21
    at Immediate.next (/Users/daixi/Documents/Code/weflex-api/node_modules/bcryptjs/dist/bcrypt.js:1078:21)
    at Immediate._onImmediate (/Users/daixi/Documents/Code/weflex-api/node_modules/async-listener/glue.js:188:31)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by yorkie** [comment]
Closed by v2.29.0 :-)
